[
  {
    _id: { $oid: "65f8a1b2c3d4e5f6a7b8c9d8" },
    name: "Luxe Nairobi Escorts",
    slug: "luxe-nairobi-escorts",
    description:
      "Premiere elite escort agency serving Nairobi's discerning clientele since 2018. We specialize in high-class companions for corporate events, luxury dates, and VIP experiences.",
    contactEmail: "bookings@luxenairobi.com",
    contactPhone: "+254712345678",
    whatsappPhone: "+254712345678",
    website: "https://luxenairobi.com",
    ownerId: { $oid: "65f8a1b2c3d4e5f6a7b8c9d3" },
    country: "Kenya",
    county: { $oid: "65f8a1b2c3d4e5f6a7b8c9d0" },
    countyCode: "047",
    region: { $oid: "65f8a1b2c3d4e5f6a7b8c9d1" },
    town: "Nairobi",
    estate: "Kilimani",
    address: "Kilimani Business Centre, 3rd Floor",
    street: "Lenana Road",
    postalCode: "00100",
    businessType: "agency",
    categories: ["elite", "corporate", "luxury", "VIP", "models"],
    openingHours: {
      monday: "09:00-22:00",
      tuesday: "09:00-22:00",
      wednesday: "09:00-22:00",
      thursday: "09:00-23:00",
      friday: "09:00-01:00",
      saturday: "10:00-02:00",
      sunday: "12:00-22:00",
    },
    services: [
      "GFE",
      "PSE",
      "Dinner Dates",
      "Travel Companion",
      "Event Escort",
      "Massage",
    ],
    specialties: [
      "Corporate Functions",
      "Luxury Travel",
      "VIP Events",
      "Foreign Clients",
    ],
    isVerified: true,
    verificationStatus: "verified",
    verificationDocuments: {
      businessLicense: "licenses/luxe-nairobi-license.jpg",
      taxCertificate: "licenses/luxe-tax-cert.jpg",
      idProof: "ids/owner-id.jpg",
    },
    logo: "agencies/luxe/logo.jpg",
    coverImage: "agencies/luxe/cover.jpg",
    gallery: [
      "agencies/luxe/gallery1.jpg",
      "agencies/luxe/gallery2.jpg",
      "agencies/luxe/gallery3.jpg",
    ],
    videos: ["agencies/luxe/video-preview.mp4"],
    establishmentYear: 2018,
    languages: ["English", "Swahili", "French", "Italian"],
    paymentMethods: ["Cash", "M-Pesa", "Bank Transfer", "Credit Card"],
    socialMedia: {
      instagram: "@luxenairobiescorts",
      twitter: "@LuxeNairobi",
      facebook: "LuxeNairobiEscorts",
      telegram: "@LuxeNairobi",
    },
    plan: {
      type: "premium",
      isActive: true,
      activatedAt: { $date: "2024-01-01T00:00:00Z" },
      expiresAt: { $date: "2025-01-01T00:00:00Z" },
      features: [
        "unlimited_employees",
        "priority_listing",
        "analytics",
        "custom_profile",
      ],
      maxEmployees: 50,
      maxGalleryImages: 100,
    },
    rating: 4.8,
    totalReviews: 156,
    totalBookings: 1200,
    totalViews: 50000,
    featuredEmployeesCount: 12,
    isActive: true,
    isFeatured: true,
    createdAt: { $date: "2024-01-15T10:00:00Z" },
    updatedAt: { $date: "2024-01-15T10:00:00Z" },
  },
  {
    _id: { $oid: "65f8a1b2c3d4e5f6a7b8c9d9" },
    name: "Nairobi Diamond Escorts",
    slug: "nairobi-diamond-escorts",
    description:
      "Trusted upscale escort agency with a reputation for professionalism and discretion. We provide refined companions for business executives and tourists visiting Nairobi.",
    contactEmail: "info@nairobidiamond.com",
    contactPhone: "+254711223344",
    whatsappPhone: "+254711223344",
    website: "https://nairobidiamondescorts.com",
    ownerId: { $oid: "65f8a1b2c3d4e5f6a7b8c9d4" },
    country: "Kenya",
    county: { $oid: "65f8a1b2c3d4e5f6a7b8c9d0" },
    countyCode: "047",
    region: { $oid: "65f8a1b2c3d4e5f6a7b8c9d1" },
    town: "Nairobi",
    estate: "Kilimani",
    address: "Diamond Plaza, 2nd Floor",
    street: "Wood Avenue",
    postalCode: "00100",
    businessType: "agency",
    categories: ["upscale", "discreet", "tourist-friendly", "professional"],
    openingHours: {
      monday: "10:00-20:00",
      tuesday: "10:00-20:00",
      wednesday: "10:00-20:00",
      thursday: "10:00-21:00",
      friday: "10:00-22:00",
      saturday: "11:00-23:00",
      sunday: "12:00-20:00",
    },
    services: [
      "GFE",
      "Social Companion",
      "Tour Guide",
      "Business Functions",
      "Massage Therapy",
    ],
    specialties: [
      "Discretion Assured",
      "Tourist Assistance",
      "Business Meetings",
    ],
    isVerified: true,
    verificationStatus: "verified",
    verificationDocuments: {
      businessLicense: "licenses/diamond-license.jpg",
      taxCertificate: "licenses/diamond-tax.jpg",
    },
    logo: "agencies/diamond/logo.png",
    coverImage: "agencies/diamond/cover.jpg",
    gallery: [
      "agencies/diamond/interior1.jpg",
      "agencies/diamond/interior2.jpg",
      "agencies/diamond/team.jpg",
    ],
    establishmentYear: 2020,
    languages: ["English", "Swahili", "German", "Spanish"],
    paymentMethods: ["Cash", "M-Pesa", "PayPal"],
    socialMedia: {
      instagram: "@NairobiDiamond",
      twitter: "@NairobiDiamondE",
      facebook: "NairobiDiamondEscorts",
    },
    plan: {
      type: "basic",
      isActive: true,
      activatedAt: { $date: "2024-03-15T00:00:00Z" },
      expiresAt: { $date: "2024-12-15T00:00:00Z" },
      features: ["standard_listing", "basic_analytics"],
      maxEmployees: 15,
      maxGalleryImages: 30,
    },
    rating: 4.6,
    totalReviews: 89,
    totalBookings: 650,
    totalViews: 32000,
    featuredEmployeesCount: 8,
    isActive: true,
    isFeatured: false,
    createdAt: { $date: "2024-01-15T10:00:00Z" },
    updatedAt: { $date: "2024-01-15T10:00:00Z" },
  },
  {
    _id: { $oid: "65f8a1b2c3d4e5f6a7b8c9da" },
    name: "Westlands Elite Companions",
    slug: "westlands-elite-companions",
    description:
      "Exclusive high-end agency located in the heart of Westlands. Catering to Nairobi's affluent residents and expatriates with sophisticated and educated companions.",
    contactEmail: "contact@westlandselite.co.ke",
    contactPhone: "+254700111222",
    whatsappPhone: "+254700111222",
    website: "https://westlandselite.co.ke",
    ownerId: { $oid: "65f8a1b2c3d4e5f6a7b8c9d5" },
    country: "Kenya",
    county: { $oid: "65f8a1b2c3d4e5f6a7b8c9d0" },
    countyCode: "047",
    region: { $oid: "65f8a1b2c3d4e5f6a7b8c9d2" },
    town: "Nairobi",
    estate: "Westlands",
    address: "The Mirage, 5th Floor",
    street: "Waiyaki Way",
    postalCode: "00100",
    businessType: "agency",
    categories: [
      "exclusive",
      "high-end",
      "educated",
      "expat-friendly",
      "luxury",
    ],
    openingHours: {
      monday: "11:00-21:00",
      tuesday: "11:00-21:00",
      wednesday: "11:00-21:00",
      thursday: "11:00-22:00",
      friday: "11:00-00:00",
      saturday: "12:00-01:00",
      sunday: "14:00-21:00",
    },
    services: [
      "VIP Companion",
      "Dinner Dates",
      "Travel Partner",
      "Social Events",
      "Corporate Functions",
    ],
    specialties: [
      "University Students",
      "Foreign Language Speakers",
      "Model Selection",
    ],
    isVerified: true,
    verificationStatus: "verified",
    verificationDocuments: {
      businessLicense: "licenses/westlands-license.pdf",
      taxCertificate: "licenses/westlands-tax.pdf",
      idProof: "ids/owner-passport.jpg",
    },
    logo: "agencies/westlands-elite/logo.jpg",
    coverImage: "agencies/westlands-elite/cover.jpg",
    gallery: [
      "agencies/westlands-elite/lounge1.jpg",
      "agencies/westlands-elite/lounge2.jpg",
      "agencies/westlands-elite/entrance.jpg",
      "agencies/westlands-elite/waiting-area.jpg",
    ],
    videos: ["agencies/westlands-elite/virtual-tour.mp4"],
    establishmentYear: 2019,
    languages: ["English", "Swahili", "French", "Chinese", "Arabic"],
    paymentMethods: [
      "Cash",
      "M-Pesa",
      "Credit Card",
      "Bank Transfer",
      "Crypto",
    ],
    socialMedia: {
      instagram: "@WestlandsElite",
      twitter: "@WestlandsEliteKE",
      facebook: "WestlandsEliteCompanions",
      telegram: "@WestlandsEliteKE",
    },
    plan: {
      type: "enterprise",
      isActive: true,
      activatedAt: { $date: "2024-01-15T00:00:00Z" },
      expiresAt: { $date: "2025-01-15T00:00:00Z" },
      features: [
        "unlimited_employees",
        "priority_support",
        "advanced_analytics",
        "custom_domain",
        "api_access",
      ],
      maxEmployees: 100,
      maxGalleryImages: 200,
    },
    rating: 4.9,
    totalReviews: 234,
    totalBookings: 1800,
    totalViews: 75000,
    featuredEmployeesCount: 15,
    isActive: true,
    isFeatured: true,
    createdAt: { $date: "2024-01-15T10:00:00Z" },
    updatedAt: { $date: "2024-01-15T10:00:00Z" },
  },
  {
    _id: { $oid: "65f8a1b2c3d4e5f6a7b8c9db" },
    name: "Capital Spa & Massage Parlor",
    slug: "capital-spa-massage-parlor",
    description:
      "Premium spa and massage parlor offering therapeutic and relaxation services with trained professionals. Our establishment provides a serene environment for stress relief and wellness.",
    contactEmail: "relax@capitalspa.co.ke",
    contactPhone: "+254722334455",
    whatsappPhone: "+254722334455",
    website: "https://capitalspanairobi.com",
    ownerId: { $oid: "65f8a1b2c3d4e5f6a7b8c9d6" },
    country: "Kenya",
    county: { $oid: "65f8a1b2c3d4e5f6a7b8c9d0" },
    countyCode: "047",
    region: { $oid: "65f8a1b2c3d4e5f6a7b8c9d2" },
    town: "Nairobi",
    estate: "Westlands",
    address: "Sarit Centre, Annex Building",
    street: "Parklands Road",
    postalCode: "00100",
    businessType: "spa",
    categories: ["spa", "massage", "wellness", "relaxation", "therapeutic"],
    openingHours: {
      monday: "09:00-20:00",
      tuesday: "09:00-20:00",
      wednesday: "09:00-20:00",
      thursday: "09:00-21:00",
      friday: "09:00-21:00",
      saturday: "10:00-19:00",
      sunday: "11:00-18:00",
    },
    services: [
      "Swedish Massage",
      "Thai Massage",
      "Deep Tissue",
      "Aromatherapy",
      "Hot Stone",
      "Reflexology",
    ],
    specialties: [
      "Stress Relief",
      "Sports Recovery",
      "Couples Massage",
      "Corporate Packages",
    ],
    isVerified: true,
    verificationStatus: "verified",
    verificationDocuments: {
      businessLicense: "licenses/capital-spa-license.jpg",
      taxCertificate: "licenses/capital-spa-tax.jpg",
      otherDocuments: [
        "licenses/health-certificate.jpg",
        "licenses/fire-safety.jpg",
      ],
    },
    logo: "agencies/capital-spa/logo.png",
    coverImage: "agencies/capital-spa/cover.jpg",
    gallery: [
      "agencies/capital-spa/spa-room1.jpg",
      "agencies/capital-spa/spa-room2.jpg",
      "agencies/capital-spa/reception.jpg",
      "agencies/capital-spa/treatment-room.jpg",
      "agencies/capital-spa/relaxation-area.jpg",
    ],
    establishmentYear: 2021,
    languages: ["English", "Swahili", "Kikuyu"],
    paymentMethods: ["Cash", "M-Pesa", "Credit Card"],
    socialMedia: {
      instagram: "@CapitalSpaNBO",
      facebook: "CapitalSpaNairobi",
    },
    plan: {
      type: "premium",
      isActive: true,
      activatedAt: { $date: "2024-02-01T00:00:00Z" },
      expiresAt: { $date: "2024-11-30T00:00:00Z" },
      features: ["unlimited_employees", "priority_listing", "booking_system"],
      maxEmployees: 25,
      maxGalleryImages: 50,
    },
    rating: 4.7,
    totalReviews: 145,
    totalBookings: 950,
    totalViews: 45000,
    featuredEmployeesCount: 6,
    isActive: true,
    isFeatured: true,
    createdAt: { $date: "2024-01-15T10:00:00Z" },
    updatedAt: { $date: "2024-01-15T10:00:00Z" },
  },
  {
    _id: { $oid: "65f8a1b2c3d4e5f6a7b8c9dc" },
    name: "Nairobi Royal Escorts Agency",
    slug: "nairobi-royal-escorts-agency",
    description:
      "Boutique agency focusing on quality over quantity. We carefully select our companions based on personality, intelligence, and professionalism to ensure memorable experiences.",
    contactEmail: "royal@nairobiescorts.agency",
    contactPhone: "+254733445566",
    whatsappPhone: "+254733445566",
    website: "https://nairobiescorts.agency",
    ownerId: { $oid: "65f8a1b2c3d4e5f6a7b8c9d7" },
    country: "Kenya",
    county: { $oid: "65f8a1b2c3d4e5f6a7b8c9d0" },
    countyCode: "047",
    region: { $oid: "65f8a1b2c3d4e5f6a7b8c9d1" },
    town: "Nairobi",
    estate: "Kilimani",
    address: "Royal Suites, Ground Floor",
    street: "Argwings Kodhek Road",
    postalCode: "00100",
    businessType: "agency",
    categories: [
      "boutique",
      "selective",
      "professional",
      "discreet",
      "quality",
    ],
    openingHours: {
      monday: "10:00-19:00",
      tuesday: "10:00-19:00",
      wednesday: "10:00-19:00",
      thursday: "10:00-20:00",
      friday: "10:00-21:00",
      saturday: "11:00-20:00",
      sunday: "12:00-18:00",
    },
    services: [
      "Companion Services",
      "Social Events",
      "Business Meetings",
      "Travel Companion",
    ],
    specialties: [
      "Boutique Selection",
      "Personality Matching",
      "Discretion Guaranteed",
    ],
    isVerified: true,
    verificationStatus: "verified",
    verificationDocuments: {
      businessLicense: "licenses/royal-license.jpg",
      idProof: "ids/owner-national-id.jpg",
    },
    logo: "agencies/royal/logo.jpg",
    coverImage: "agencies/royal/cover.jpg",
    gallery: ["agencies/royal/office1.jpg", "agencies/royal/meeting-room.jpg"],
    establishmentYear: 2022,
    languages: ["English", "Swahili"],
    paymentMethods: ["Cash", "M-Pesa"],
    socialMedia: {
      instagram: "@NairobiRoyalAgency",
      twitter: "@NairobiRoyalEsc",
    },
    plan: {
      type: "basic",
      isActive: true,
      activatedAt: { $date: "2024-04-01T00:00:00Z" },
      expiresAt: { $date: "2024-12-31T00:00:00Z" },
      features: ["standard_listing"],
      maxEmployees: 10,
      maxGalleryImages: 20,
    },
    rating: 4.5,
    totalReviews: 67,
    totalBookings: 420,
    totalViews: 28000,
    featuredEmployeesCount: 5,
    isActive: true,
    isFeatured: false,
    createdAt: { $date: "2024-01-15T10:00:00Z" },
    updatedAt: { $date: "2024-01-15T10:00:00Z" },
  },
];
